server.port=8081
spring.application.name=paciente-service

# Configuraci�n de Base de Datos (Ajusta tus credenciales)
spring.datasource.url=jdbc:mysql://localhost:3306/db_pacientes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Oli2003.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/